{"name": "Попытка изменения почты авторизованного пользователя на уже существующую почту", "status": "failed", "statusDetails": {"message": "AssertionError: assert (200 == 403)\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_user.TestUpdateUser object at 0x000002B3CAB2F150>\ncreate_and_delete_user = (<Response [200]>, {'email': 'cklozwybto@yandex.ru', 'name': 'fkwlzenmgb', 'password': 'guszzvmtgp'}, {'email': 'ckloz...DY1OWVkMjgwMDAxYjNhMWNiYiIsImlhdCI6MTcwNDY3MDMwOSwiZXhwIjoxNzA0NjcxNTA5fQ.7NmEv4FSFd8tCv3182jcvvALWDOAfO9if2SC7F_e1Ew')\n\n    @allure.title('Попытка изменения почты авторизованного пользователя на уже существующую почту')\n    def test_update_user_email_of_signed_in_user(self, create_and_delete_user):\n        new_email = {\"email\": create_and_delete_user[2]['email']}\n        token = {'Authorization': create_and_delete_user[3]}\n        response = requests.patch(Links.user_url, headers=token, data=new_email)\n>       assert response.status_code == 403 and response.json()['message'] == \"User with such email already exists\"\nE       assert (200 == 403)\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_user.py:62: AssertionError"}, "start": 1704670304927, "stop": 1704670306353, "uuid": "9230fa2d-4bc1-41ce-9bce-59b209116161", "historyId": "f254c435c6a05b2a4e8b055f44ea9e80", "testCaseId": "f254c435c6a05b2a4e8b055f44ea9e80", "fullName": "tests.test_user.TestUpdateUser#test_update_user_email_of_signed_in_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUpdateUser"}, {"name": "host", "value": "LAPTOP-EMEFLSN2"}, {"name": "thread", "value": "6280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}